title = "Adonis"
gitRepoUrl = "https://github.com/Sceleratis/Adonis_2.0"
gitSourceBranch = "main"

[home]
enabled = true
includeReadme = false

[docusaurus]
tagline = "Roblox Server Administration System"
favicon = "/favicon.png"

[footer]
style = "dark"
copyright = "Copyright © 2022 Sceleratis/Epix Incorporated & The Adonis Development Community. Built with Moonwave and Docusaurus"
