title = "Adonis"
gitRepoUrl = "https://github.com/Sceleratis/Adonis_2.0"
gitSourceBranch = "main"

[home]
enabled = true
includeReadme = true

[docusaurus]
tagline = "Roblox Server Administration System"
favicon = "/favicon.png"

[[navbar.items]]
href = "https://discord.gg/H5RvTP3"
label = "Discord"
position = "right"

[footer]
style = "dark"
copyright = "Copyright © 2022 Epix Incorporated and Adonis Contributors. Built with Moonwave and Docusaurus"
