name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "👋 Welcome! It looks like this is your first time creating an issue here. Keep in mind that Adonis 2.0 is still heavily under development, and we'll try our best to fix any bugs that come up."
        pr-message: "👋 Hello there! It looks like this is your first time contributing to the Adonis 2.0 project. Please be sure to have read the Contribution Guidelines! Good luck!"
